# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded ansifmt 0.1 [list source [file join $dir ansifmt.tcl]]
package ifneeded getopt 2008.12.07 [list source [file join $dir getopt.tcl]]
package ifneeded kvlookup 0.1 [list source [file join $dir kvlookup.tcl]]
package ifneeded logging 0.1 [list source [file join $dir logging.tcl]]
package ifneeded missing 1.0 [list source [file join $dir missing.tcl]]
package ifneeded platinfo 0.1 [list source [file join $dir platinfo.tcl]]
package ifneeded runprog 1.0 [list source [file join $dir runprog.tcl]]
package ifneeded sds 1.0 [list source [file join $dir sds.tcl]]
package ifneeded tagline 1.0 [list source [file join $dir tagline.tcl]]
