# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded ansifmt 0.1 [list source [file join $dir ansifmt.tcl]]
package ifneeded direnv 0.1 [list source [file join $dir direnv.tcl]]
package ifneeded formats 0.1 [list source [file join $dir formats.tcl]]
package ifneeded fsextra 0.1 [list source [file join $dir fsextra.tcl]]
package ifneeded getopt 2008.12.07 [list source [file join $dir getopt.tcl]]
package ifneeded json 0.1 [list source [file join $dir json.tcl]]
package ifneeded jsonparse 1.0 [list source [file join $dir json-parser.tcl]]
package ifneeded kvlookup 0.1 [list source [file join $dir kvlookup.tcl]]
package ifneeded logging 0.1 [list source [file join $dir logging.tcl]]
package ifneeded meuri 0.1 [list source [file join $dir meuri.tcl]]
package ifneeded missing 1.1 [list source [file join $dir missing.tcl]]
package ifneeded mkyaml 0.1 [list source [file join $dir mkyaml.tcl]]
package ifneeded oscmd 0.1 [list source [file join $dir oscmd.tcl]]
package ifneeded platinfo 0.1 [list source [file join $dir platinfo.tcl]]
package ifneeded runner 0.1 [list source [file join $dir runner.tcl]]
package ifneeded sds 1.0 [list source [file join $dir sds.tcl]]
package ifneeded setops 0.1 [list source [file join $dir setops.tcl]]
package ifneeded tagline 0.1 [list source [file join $dir tagline.tcl]]
package ifneeded tomlfile 0.1 [list source [file join $dir tomlfile.tcl]]
